---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-gke-pyapp-dev-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template:
    metadata:
      labels:
        app: gcp
    spec:
      containers:
      - name: devops-gke-pyapp-dev
        image: gcr.io/steel-binder-384114/devops-gke-pyapp-dev:latest
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"


---
apiVersion: v1
kind: Service
metadata:
  name: devops-gke-pyapp-dev-service
  namespace: gcp-devops-dev
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  selector:
    app: gcp
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 5000
  type: "LoadBalancer"







